---
# tasks file for ssl
- name: Ensure Key folder {{ ssl_key_path }}
  file:
    path: "{{ ssl_key_path }}"
    state: directory
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_key_umask }}"
  when:
    - ssl_cert is defined
    - ssl_key is defined

- name: copy SSLCertificateFile {{ ssl_cert }}
  copy:
    src: "{{ ssl_cert }}"
    dest: "{{ ssl_cert_path }}/{{ ssl_crt_name }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_cert_umask }}"
  when:
    - ssl_cert is defined
    - ssl_key is defined

- name: copy SSLCertificateKeyFile {{ ssl_key }}
  copy:
    src: "{{ ssl_key }}"
    dest: "{{ ssl_key_path }}/{{ ssl_key_name }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_key_umask }}"
  when:
    - ssl_cert is defined
    - ssl_key is defined

- name: copy SSLCertificateChainFile {{ ssl_ica }}
  copy:
    content: "{{ ssl_ica }}"
    dest: "{{ ssl_cert_path }}/{{ ssl_ica_name }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: "{{ ssl_cert_umask }}"
  when:
    - ssl_cert is defined
    - ssl_key is defined
    - ssl_ica is defined
